// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _ripserR_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// test_ripser_print
void test_ripser_print();
RcppExport SEXP _ripserR_test_ripser_print() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    test_ripser_print();
    return R_NilValue;
END_RCPP
}
// test_ripser
List test_ripser();
RcppExport SEXP _ripserR_test_ripser() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_ripser());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ripserR_rcpp_hello_world", (DL_FUNC) &_ripserR_rcpp_hello_world, 0},
    {"_ripserR_test_ripser_print", (DL_FUNC) &_ripserR_test_ripser_print, 0},
    {"_ripserR_test_ripser", (DL_FUNC) &_ripserR_test_ripser, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_ripserR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
