# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_ripserR_rcpp_hello_world`)
}

test_ripser_print <- function() {
    invisible(.Call(`_ripserR_test_ripser_print`))
}

test_ripser <- function() {
    .Call(`_ripserR_test_ripser`)
}

