// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _ripserAPI_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// ripser_test
Rcpp::List ripser_test(NumericVector vec);
RcppExport SEXP _ripserAPI_ripser_test(SEXP vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vec(vecSEXP);
    rcpp_result_gen = Rcpp::wrap(ripser_test(vec));
    return rcpp_result_gen;
END_RCPP
}
// ripser_sparseInput_test
Rcpp::List ripser_sparseInput_test(Rcpp::NumericVector sparseVec);
RcppExport SEXP _ripserAPI_ripser_sparseInput_test(SEXP sparseVecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sparseVec(sparseVecSEXP);
    rcpp_result_gen = Rcpp::wrap(ripser_sparseInput_test(sparseVec));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ripserAPI_rcpp_hello_world", (DL_FUNC) &_ripserAPI_rcpp_hello_world, 0},
    {"_ripserAPI_ripser_test", (DL_FUNC) &_ripserAPI_ripser_test, 1},
    {"_ripserAPI_ripser_sparseInput_test", (DL_FUNC) &_ripserAPI_ripser_sparseInput_test, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_ripserAPI(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
